aws:
  vpc_name: skypilot-vpc
  use_internal_ips: true
  use_ssm: true
  remote_identity: SERVICE_ACCOUNT
  prioritize_reservations: true
  specific_reservations:
    - "cr-0b499ab7fbcdab23c"
    - "cr-0de49c0884c3f7351"
